### ISSUE TITLE
Speedbooster in Main Street Missile location

### ISSUE THREAD

**Issue by randomcodegen** [aremath/sm_rando#3]
Not sure if this is a bug or not as I got speedbooster from a different location earlier in the seed.
By the way, is there a way to contact you on discord? I have some questions about rules in rooms.txt
![sm](https://user-images.githubusercontent.com/46383843/71718181-b04bb380-2e1a-11ea-80ef-72caac7d1b95.PNG)

**Comment by aremath** [comment]
Depending on the settings, that's probably not a bug (although maybe it should be?). The default setting is to place two of every major item. The first placement for every major is determined by a search that ensures that you can complete the seed, but the second placement is essentially random. Because the second placement isn't checked, you can wind up with stupid placements like speedbooster in a speed-locked location.

For that specific item location, I encode it as completely unreachable, because short-charges should not be required (the logic I wrote is for casual players). Thus, the item you find there will never actually matter for being able to complete the seed.

You can message me on Discord (I'm also Aremath there). I also hang out in the metconst discord channel.
